version: '3'
services:
  mysql:
    build: /vagrant/srcs/mysql
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wp_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
  wordpress:
    build: /vagrant/srcs/wordpress
    volumes:
      - /data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always
  nginx:
    build: /vagrant/srcs/nginx
    volumes:
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress