apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: sharing_key
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: wp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-claim
      containers:
      - name: wordpress
        image: wp_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
